# **1. Cargamos los datos e importamos librerías**

In [2]:
# 1. Reiniciar el runtime primero (menú: Runtime → Restart runtime)

# 2. Instalar versiones compatibles con el entorno de Colab
# Fijar pandas y numpy a versiones compatibles con google-colab y tensorflow
!pip install --upgrade \
    numpy==1.26.4 \
    pandas==2.2.2 \
    scipy>=1.14.0 \
    matplotlib>=3.9.0 \
    scikit-learn>=1.5.0 \
    seaborn>=0.13.0 \
    dython>=0.7.0 \
    --force-reinstall

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.34.0 requires jedi>=0.16, which is not installed.
opencv-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
shap 0.51.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
xarray-einstats 0.10.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
gradio 5.50.0 requires pillow<12.0,>=8.0, but you have pillow 12.2.0 which is incompatible.
tobler 0.13.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
pytensor 2.38.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
cupy-cuda12x 14.0.1 requires numpy<2.6,>=2.0, but you have numpy 1.26.4 which is incompatible.

In [3]:
# Me niego a usar NumPy <2.x en un entorno virtual

!pip install --upgrade \
    "numpy==2.0.2" \
    "pandas==2.2.2" \
    "scipy==1.17.1" \
    "matplotlib>=3.10.8" \
    "scikit-learn==1.8.0" \
    "seaborn==0.13.2" \
    "jedi==0.19.2" \
    "pillow==11.0.0"\
    "setuptools==70.0.0"\
    --force-reinstall

!pip install "dython>=0.7.12" --no-deps

Collecting numpy==2.0.2
  Downloading numpy-2.0.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.9/60.9 kB 2.5 MB/s eta 0:00:00
Collecting pandas==2.2.2
  Using cached pandas-2.2.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (19 kB)
Collecting scipy==1.17.1
  Using cached scipy-1.17.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
Collecting matplotlib>=3.10.8
  Using cached matplotlib-3.10.8-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (52 kB)
Collecting scikit-learn==1.8.0
  Using cached scikit_learn-1.8.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (11 kB)
Collecting seaborn==0.13.2
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting jedi==0.19.2
  Downloading jedi-0.19.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting pillow==11.0.0
  Downloading pillow-11.0.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (9.1 kB)
Collecting setuptools==70.0.0
  Downloading setuptools-70.0.0-py3-none-any.whl.metadata (5.9 kB)
Collecting python-dateutil>=2.8.2 (from pandas==2.2.2)
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting pytz>=2020.1 (from pandas==2.2.2)
  Using cached pytz-2026.1.post1-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas==2.2.2)
  Using cached tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting joblib>=1.3.0 (from scikit-learn==1.8.0)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn==1.8.0)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Collecting parso<0.9.0,>=0.8.4 (from jedi==0.19.2)
  Downloading parso-0.8.6-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting contourpy>=1.0.1 (from matplotlib>=3.10.8)
  Using cached contourpy-1.3.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib>=3.10.8)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib>=3.10.8)
  Using cached fonttools-4.62.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (117 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib>=3.10.8)
  Using cached kiwisolver-1.5.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (5.1 kB)
Collecting packaging>=20.0 (from matplotlib>=3.10.8)
  Using cached packaging-26.0-py3-none-any.whl.metadata (3.3 kB)
Collecting pyparsing>=3 (from matplotlib>=3.10.8)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas==2.2.2)
  Using cached six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Downloading numpy-2.0.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (19.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.2/19.2 MB 102.4 MB/s eta 0:00:00
Using cached pandas-2.2.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.7 MB)
Using cached scipy-1.17.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (35.2 MB)
Using cached scikit_learn-1.8.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (8.9 MB)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Downloading jedi-0.19.2-py2.py3-none-any.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 79.9 MB/s eta 0:00:00
Downloading pillow-11.0.0-cp312-cp312-manylinux_2_28_x86_64.whl (4.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.4/4.4 MB 66.4 MB/s eta 0:00:00
Downloading setuptools-70.0.0-py3-none-any.whl (863 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 863.4/863.4 kB 65.3 MB/s eta 0:00:00
Using cached matplotlib-3.10.8-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (8.7 MB)
Using cached contourpy-1.3.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (362 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached fonttools-4.62.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (5.0 MB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Using cached kiwisolver-1.5.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.5 MB)
Using cached packaging-26.0-py3-none-any.whl (74 kB)
Downloading parso-0.8.6-py2.py3-none-any.whl (106 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.9/106.9 kB 11.4 MB/s eta 0:00:00
Using cached pyparsing-3.3.2-py3-none-any.whl (122 kB)
Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Using cached pytz-2026.1.post1-py2.py3-none-any.whl (510 kB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Using cached tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Using cached six-1.17.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: pytz, tzdata, threadpoolctl, six, setuptools, pyparsing, pillow, parso, packaging, numpy, kiwisolver, joblib, fonttools, cycler, scipy, python-dateutil, jedi, contourpy, scikit-learn, pandas, matplotlib, seaborn
  Attempting uninstall: pytz
    Found existing installation: pytz 2026.1.post1
    Uninstalling pytz-2026.1.post1:
      Successfully uninstalled pytz-2026.1.post1
  Attempting uninstall: tzdata
    Found existing installation: tzdata 2025.3
    Uninstalling tzdata-2025.3:
      Successfully uninstalled tzdata-2025.3
  Attempting uninstall: threadpoolctl
    Found existing installation: threadpoolctl 3.6.0
    Uninstalling threadpoolctl-3.6.0:
      Successfully uninstalled threadpoolctl-3.6.0
  Attempting uninstall: six
    Found existing installation: six 1.17.0
    Uninstalling six-1.17.0:
      Successfully uninstalled six-1.17.0
  Attempting uninstall: setuptools
    Found existing installation: setuptools 82.0.1
    Uninstalling setuptools-82.0.1:
      Successfully uninstalled setuptools-82.0.1
  Attempting uninstall: pyparsing
    Found existing installation: pyparsing 3.3.2
    Uninstalling pyparsing-3.3.2:
      Successfully uninstalled pyparsing-3.3.2
  Attempting uninstall: pillow
    Found existing installation: pillow 12.2.0
    Uninstalling pillow-12.2.0:
      Successfully uninstalled pillow-12.2.0
  Attempting uninstall: parso
    Found existing installation: parso 0.8.6
    Uninstalling parso-0.8.6:
      Successfully uninstalled parso-0.8.6
  Attempting uninstall: packaging
    Found existing installation: packaging 26.0
    Uninstalling packaging-26.0:
      Successfully uninstalled packaging-26.0
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
  Attempting uninstall: kiwisolver
    Found existing installation: kiwisolver 1.5.0
    Uninstalling kiwisolver-1.5.0:
      Successfully uninstalled kiwisolver-1.5.0
  Attempting uninstall: joblib
    Found existing installation: joblib 1.5.3
    Uninstalling joblib-1.5.3:
      Successfully uninstalled joblib-1.5.3
  Attempting uninstall: fonttools
    Found existing installation: fonttools 4.62.1
    Uninstalling fonttools-4.62.1:
      Successfully uninstalled fonttools-4.62.1
  Attempting uninstall: cycler
    Found existing installation: cycler 0.12.1
    Uninstalling cycler-0.12.1:
      Successfully uninstalled cycler-0.12.1
  Attempting uninstall: scipy
    Found existing installation: scipy 1.17.1
    Uninstalling scipy-1.17.1:
      Successfully uninstalled scipy-1.17.1
  Attempting uninstall: python-dateutil
    Found existing installation: python-dateutil 2.9.0.post0
    Uninstalling python-dateutil-2.9.0.post0:
      Successfully uninstalled python-dateutil-2.9.0.post0
  Attempting uninstall: contourpy
    Found existing installation: contourpy 1.3.3
    Uninstalling contourpy-1.3.3:
      Successfully uninstalled contourpy-1.3.3
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.8.0
    Uninstalling scikit-learn-1.8.0:
      Successfully uninstalled scikit-learn-1.8.0
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.2
    Uninstalling pandas-2.2.2:
      Successfully uninstalled pandas-2.2.2
  Attempting uninstall: matplotlib
    Found existing installation: matplotlib 3.10.8
    Uninstalling matplotlib-3.10.8:
      Successfully uninstalled matplotlib-3.10.8
  Attempting uninstall: seaborn
    Found existing installation: seaborn 0.13.2
    Uninstalling seaborn-0.13.2:
      Successfully uninstalled seaborn-0.13.2
Successfully installed contourpy-1.3.3 cycler-0.12.1 fonttools-4.62.1 jedi-0.19.2 joblib-1.5.3 kiwisolver-1.5.0 matplotlib-3.10.8 numpy-2.0.2 packaging-26.0 pandas-2.2.2 parso-0.8.6 pillow-11.0.0 pyparsing-3.3.2 python-dateutil-2.9.0.post0 pytz-2026.1.post1 scikit-learn-1.8.0 scipy-1.17.1 seaborn-0.13.2 setuptools-70.0.0 six-1.17.0 threadpoolctl-3.6.0 tzdata-2025.3

Collecting dython>=0.7.12
  Using cached dython-0.7.12-py3-none-any.whl.metadata (3.4 kB)
Downloading dython-0.7.12-py3-none-any.whl (26 kB)
Installing collected packages: dython
  Attempting uninstall: dython
    Found existing installation: dython 0.7.10
    Uninstalling dython-0.7.10:
      Successfully uninstalled dython-0.7.10
Successfully installed dython-0.7.12

In [4]:
import pandas as pd
import numpy as np
import dython
import PIL.Image

print(f"✅ Numpy: {np.__version__} (Correcto: >2.0)")
print(f"✅ Pandas: {pd.__version__} (Correcto: 2.2.2)")
print(f"✅ Dython: {dython.__version__}")
print(f"✅ Pillow: {PIL.Image.__version__} (Correcto: 11.0.0)")

from dython.nominal import associations
print("\n🔥 ¡Todo configurado correctamente! Ya puedes trabajar.")

✅ Numpy: 2.0.2 (Correcto: >2.0)
✅ Pandas: 2.2.2 (Correcto: 2.2.2)
✅ Dython: 0.7.12
✅ Pillow: 11.3.0 (Correcto: 11.0.0)

🔥 ¡Todo configurado correctamente! Ya puedes trabajar.

In [5]:
# Cargar los datos

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder,MinMaxScaler, OrdinalEncoder
import polars as pl

In [7]:
df_socio= pd.read_csv('/content/drive/MyDrive/TFM/customer_sociodemographics.csv')
df_comm= pd.read_csv('/content/drive/MyDrive/TFM/customer_commercial_activity.csv')
df_prod= pd.read_csv('/content/drive/MyDrive/TFM/customer_products.csv')
df_prod_desc= pd.read_csv('/content/drive/MyDrive/TFM/product_description.csv')
df_sales= pd.read_csv('/content/drive/MyDrive/TFM/sales.csv')

# **2. Limpieza de datos, imputamos nulos**

In [8]:
def limpiar_columnas_basura(df):
    cols_to_drop = [c for c in df.columns if 'Unnamed' in c]
    if cols_to_drop:
        print(f"🗑️ Eliminando columnas basura: {cols_to_drop}")
        df.drop(columns=cols_to_drop, inplace=True)
    return df

df_prod = limpiar_columnas_basura(df_prod)
df_socio = limpiar_columnas_basura(df_socio)
df_comm = limpiar_columnas_basura(df_comm)
df_sales = limpiar_columnas_basura(df_sales)
df_prod_desc = limpiar_columnas_basura(df_prod_desc)

🗑️ Eliminando columnas basura: ['Unnamed: 0']
🗑️ Eliminando columnas basura: ['Unnamed: 0']
🗑️ Eliminando columnas basura: ['Unnamed: 0']
🗑️ Eliminando columnas basura: ['Unnamed: 0']
🗑️ Eliminando columnas basura: ['Unnamed: 0']

In [9]:
# SQL Equivalente:
# SELECT s.*, d.product_desc
# FROM sales s
# LEFT JOIN product_description d ON s.product_ID = d.pk_product_ID;

# En Pandas:
df_ventas_enriquecida = pd.merge(
    df_sales,
    df_prod_desc,
    left_on='product_ID',
    right_on='pk_product_ID',
    how='left'
)
df_ventas_enriquecida.head(20)

,pk_sale,cid,month_sale,product_ID,net_margin,pk_product_ID,product_desc,family_product
0,6666,33620,2018-05-01,2335,952.9,2335,short_term_deposit,investment
1,6667,35063,2018-06-01,2335,1625.2,2335,short_term_deposit,investment
2,6668,37299,2018-02-01,2335,1279.7,2335,short_term_deposit,investment
3,6669,39997,2018-02-01,2335,1511.9,2335,short_term_deposit,investment
4,6670,44012,2018-02-01,2335,1680.3,2335,short_term_deposit,investment
5,6671,66770,2018-06-01,2335,1772.0,2335,short_term_deposit,investment
6,6672,100296,2018-04-01,2335,1391.9,2335,short_term_deposit,investment
7,6673,101658,2018-08-01,2335,1466.7,2335,short_term_deposit,investment
8,6674,114080,2018-03-01,2335,1772.9,2335,short_term_deposit,investment
9,6675,124554,2018-10-01,2335,1534.5,2335,short_term_deposit,investment
10,6676,132830,2018-03-01,2335,1366.7,2335,short_term_deposit,investment
11,6677,148406,2018-02-01,2335,1524.1,2335,short_term_deposit,investment
12,6678,151135,2018-03-01,2335,1867.6,2335,short_term_deposit,investment
13,6679,168399,2018-03-01,2335,1147.5,2335,short_term_deposit,investment
14,6680,181756,2018-04-01,2335,1253.9,2335,short_term_deposit,investment
15,6681,200174,2018-07-01,2335,1952.3,2335,short_term_deposit,investment
16,6682,204296,2018-07-01,2335,1495.7,2335,short_term_deposit,investment
17,6683,205204,2018-04-01,2335,1378.2,2335,short_term_deposit,investment
18,6684,221716,2018-10-01,2335,1410.6,2335,short_term_deposit,investment
19,6685,224523,2018-04-01,2335,717.2,2335,short_term_deposit,investment

In [10]:
# SQL Equivalente:
# SELECT * FROM sociodemo s
# JOIN commercial c ON s.pk_cid = c.pk_cid AND s.pk_partition = c.pk_partition

# En Pandas:
df_master = pd.merge(
    df_socio,
    df_comm,
    on=['pk_cid', 'pk_partition'],
    how='inner',
    validate='1:1'
)
df_master.head(20)

,pk_cid,pk_partition,country_id,region_code,gender,age,deceased,salary,entry_date,entry_channel,active_customer,segment
0,1375586,2018-01,ES,29.0,H,35,N,87218.10,2018-01,KHL,1.0,02 - PARTICULARES
1,1050611,2018-01,ES,13.0,V,23,N,35548.74,2015-08,KHE,0.0,03 - UNIVERSITARIO
2,1050612,2018-01,ES,13.0,V,23,N,122179.11,2015-08,KHE,0.0,03 - UNIVERSITARIO
3,1050613,2018-01,ES,50.0,H,22,N,119775.54,2015-08,KHD,0.0,03 - UNIVERSITARIO
4,1050614,2018-01,ES,50.0,V,23,N,NaN,2015-08,KHE,1.0,03 - UNIVERSITARIO
5,1050615,2018-01,ES,45.0,H,23,N,22220.04,2015-08,KHE,0.0,03 - UNIVERSITARIO
6,1050616,2018-01,ES,24.0,H,23,N,295590.36,2015-08,KHE,0.0,03 - UNIVERSITARIO
7,1050617,2018-01,ES,50.0,H,23,N,113316.66,2015-08,KHE,1.0,03 - UNIVERSITARIO
8,1050619,2018-01,ES,20.0,H,24,N,NaN,2015-08,KHE,0.0,03 - UNIVERSITARIO
9,1050620,2018-01,ES,10.0,H,23,N,113194.98,2015-08,KHE,0.0,03 - UNIVERSITARIO
10,1050621,2018-01,ES,50.0,V,23,N,72575.88,2015-08,KHE,0.0,03 - UNIVERSITARIO
11,1050622,2018-01,ES,17.0,H,23,N,NaN,2015-08,KHE,0.0,03 - UNIVERSITARIO
12,1050623,2018-01,ES,49.0,H,23,N,113538.81,2015-08,KHE,1.0,03 - UNIVERSITARIO
13,1050624,2018-01,ES,50.0,H,65,N,61605.09,2015-08,KHE,1.0,02 - PARTICULARES
14,1050625,2018-01,ES,49.0,V,23,N,NaN,2015-08,KHE,1.0,03 - UNIVERSITARIO
15,1050626,2018-01,ES,8.0,V,23,N,NaN,2015-08,KHE,1.0,03 - UNIVERSITARIO
16,1050610,2018-01,ES,37.0,V,24,N,68318.46,2015-08,KHE,1.0,03 - UNIVERSITARIO
17,1050627,2018-01,ES,13.0,H,23,N,65608.35,2015-08,KHE,0.0,03 - UNIVERSITARIO
18,1050609,2018-01,ES,13.0,H,22,N,73432.47,2015-08,KFA,1.0,03 - UNIVERSITARIO
19,1050605,2018-01,ES,45.0,V,23,N,NaN,2015-08,KHE,0.0,03 - UNIVERSITARIO

In [11]:
# Fusionamos df_prod al df_master que ya tienes
df_master = pd.merge(
    df_master,
    df_prod,
    on=['pk_cid', 'pk_partition'],
    how='inner',
    validate='1:1'
)
print(df_master.shape)
df_master.head(20)

(5962924, 27)

,pk_cid,pk_partition,country_id,region_code,gender,age,deceased,salary,entry_date,entry_channel,...,long_term_deposit,em_account_pp,credit_card,payroll,pension_plan,payroll_account,emc_account,debit_card,em_account_p,em_acount
0,1375586,2018-01,ES,29.0,H,35,N,87218.10,2018-01,KHL,...,0,0,0,0.0,0.0,0,0,0,0,1
1,1050611,2018-01,ES,13.0,V,23,N,35548.74,2015-08,KHE,...,0,0,0,0.0,0.0,0,0,0,0,1
2,1050612,2018-01,ES,13.0,V,23,N,122179.11,2015-08,KHE,...,0,0,0,0.0,0.0,0,0,0,0,1
3,1050613,2018-01,ES,50.0,H,22,N,119775.54,2015-08,KHD,...,0,0,0,0.0,0.0,0,0,0,0,0
4,1050614,2018-01,ES,50.0,V,23,N,NaN,2015-08,KHE,...,0,0,0,0.0,0.0,0,0,0,0,1
5,1050615,2018-01,ES,45.0,H,23,N,22220.04,2015-08,KHE,...,0,0,0,0.0,0.0,0,0,0,0,1
6,1050616,2018-01,ES,24.0,H,23,N,295590.36,2015-08,KHE,...,0,0,0,0.0,0.0,0,0,0,0,1
7,1050617,2018-01,ES,50.0,H,23,N,113316.66,2015-08,KHE,...,0,0,0,0.0,0.0,0,0,0,0,1
8,1050619,2018-01,ES,20.0,H,24,N,NaN,2015-08,KHE,...,0,0,0,0.0,0.0,0,0,0,0,1
9,1050620,2018-01,ES,10.0,H,23,N,113194.98,2015-08,KHE,...,0,0,0,0.0,0.0,0,0,0,0,1
10,1050621,2018-01,ES,50.0,V,23,N,72575.88,2015-08,KHE,...,0,0,0,0.0,0.0,0,0,0,0,1
11,1050622,2018-01,ES,17.0,H,23,N,NaN,2015-08,KHE,...,0,0,0,0.0,0.0,0,0,0,0,1
12,1050623,2018-01,ES,49.0,H,23,N,113538.81,2015-08,KHE,...,0,0,0,0.0,0.0,0,0,0,0,1
13,1050624,2018-01,ES,50.0,H,65,N,61605.09,2015-08,KHE,...,0,0,0,0.0,0.0,0,0,0,0,1
14,1050625,2018-01,ES,49.0,V,23,N,NaN,2015-08,KHE,...,0,0,0,0.0,0.0,0,0,0,0,1
15,1050626,2018-01,ES,8.0,V,23,N,NaN,2015-08,KHE,...,0,0,0,0.0,0.0,0,0,0,0,1
16,1050610,2018-01,ES,37.0,V,24,N,68318.46,2015-08,KHE,...,0,0,0,0.0,0.0,0,0,0,0,1
17,1050627,2018-01,ES,13.0,H,23,N,65608.35,2015-08,KHE,...,0,0,0,0.0,0.0,0,0,0,0,1
18,1050609,2018-01,ES,13.0,H,22,N,73432.47,2015-08,KFA,...,0,0,0,0.0,0.0,0,0,0,0,1
19,1050605,2018-01,ES,45.0,V,23,N,NaN,2015-08,KHE,...,0,0,0,0.0,0.0,0,0,0,0,1

In [12]:
df_master_t = df_master.sort_values(by=['pk_cid', 'pk_partition'])
df_master_t['country_id'] = df_master['country_id'].mask(df_master['country_id'] != 'ES', 'Other')
df_master_t['region_code'] = df_master['region_code'].mask(df_master_t['country_id'] == 'Other', -1.0)

In [13]:
df_master_t.drop('em_account_p', axis=1, inplace=True)
df_master_t.drop('em_account_pp', axis=1, inplace=True)

In [14]:
# 1. Definimos las columnas
group_cols = ['segment', 'region_code']
target_col = 'salary'

# 2. Calculamos el valor de relleno por grupo (usamos mediana por ser salario)
fill_values = df_master_t.groupby(group_cols)[target_col].median().reset_index()
fill_values.rename(columns={target_col: 'fill_value'}, inplace=True)

# 3. Calculamos el valor global de rescate (por si algún grupo entero es NaN)
global_fallback = df_master_t[target_col].median()

print(f"Mediana global de rescate: {global_fallback}")
print(fill_values.head())

# 4. Hacemos el cruce (merge) del dataframe original con los valores de relleno
df_merged = df_master_t.merge(fill_values, on=group_cols, how='left')

# 5. Rellenamos los nulos directamente en nuestro dataframe original
# Paso A: Rellenamos con el valor de su grupo (segment + region_code)
df_master_t[target_col] = df_master_t[target_col].fillna(df_merged['fill_value'])

# Paso B: Si algún cliente tenía un segmento/región sin ningún salario conocido, usamos el global
df_master_t[target_col] = df_master_t[target_col].fillna(global_fallback)

# Comprobación final
nulos_restantes = df_master_t[target_col].isnull().sum()
print(f"Nulos restantes en {target_col}: {nulos_restantes}")

Mediana global de rescate: 88441.47
    segment  region_code  fill_value
0  01 - TOP         -1.0   114949.44
1  01 - TOP          1.0    55271.07
2  01 - TOP          2.0   109153.11
3  01 - TOP          3.0    75030.72
4  01 - TOP          4.0    85991.10
Nulos restantes en salary: 0

In [15]:
# Calcula la moda de la columna 'payroll'
moda_payroll = df_master_t['payroll'].mode()[0]  # mode() devuelve una Serie, [0] toma el primer valor
df_master_t['payroll'] = df_master_t['payroll'].fillna(moda_payroll)

# Calcula la moda de la columna 'pension_plan'
moda_pension_plan = df_master_t['pension_plan'].mode()[0]  # mode() devuelve una Serie, [0] toma el primer valor
df_master_t['pension_plan'] = df_master_t['pension_plan'].fillna(moda_pension_plan)

In [16]:
mode_value_region_code=df_master_t["region_code"].mode()[0]
mode_value_gender=df_master_t["gender"].mode()[0]
mode_value_entry_channel=df_master_t["entry_channel"].mode()[0]
mode_value_segment=df_master_t["segment"].mode()[0]

# Rellena los nulos con la media
df_master_t["region_code"] = df_master_t["region_code"].fillna(mode_value_region_code)
df_master_t["gender"] = df_master_t["gender"].fillna(mode_value_gender)
df_master_t["entry_channel"] = df_master_t["entry_channel"].fillna(mode_value_entry_channel)
df_master_t["segment"] = df_master_t["segment"].fillna(mode_value_segment)

In [ ]:
df_master_t.isnull().sum()

pk_cid                0
pk_partition          0
country_id            0
region_code           0
gender                0
age                   0
deceased              0
salary                0
entry_date            0
entry_channel         0
active_customer       0
segment               0
short_term_deposit    0
loans                 0
mortgage              0
funds                 0
securities            0
long_term_deposit     0
credit_card           0
payroll               0
pension_plan          0
payroll_account       0
emc_account           0
debit_card            0
em_acount             0
dtype: int64

In [17]:
# Extraer los primeros 7 caracteres (YYYY-MM) de month_sale
df_ventas_enriquecida['month_sale'] = df_ventas_enriquecida['month_sale'].str[:7]

# Ver tipos de datos
print("df_master_t.dtypes:\n", df_master_t[['pk_cid', 'pk_partition']].dtypes)
print("\ndf_ventas_enriquecida.dtypes:\n", df_ventas_enriquecida[['cid', 'month_sale']].dtypes)

# 1. Ver el tamaño de ambos DataFrames
print("Tamaño df_master_t:", df_master_t.shape)
print("Tamaño df_sales:", df_ventas_enriquecida.shape)

# 2. Ver cuántas filas del merge tienen coincidencia (non-null en alguna columna de ventas)
coincidencias = df_ventas_enriquecida['pk_sale'].notnull().sum()
print(f"Filas con ventas (coincidencias): {coincidencias}")
print(f"Filas sin ventas (nulos): {df_ventas_enriquecida['pk_sale'].isnull().sum()}")

# 3. Porcentaje de coincidencia
total = len(df_master_t)
print(f"Porcentaje de coincidencia: {coincidencias/total*100:.2f}%")

df_master_t.dtypes:
 pk_cid           int64
pk_partition    object
dtype: object

df_ventas_enriquecida.dtypes:
 cid            int64
month_sale    object
dtype: object
Tamaño df_master_t: (5962924, 25)
Tamaño df_sales: (240773, 8)
Filas con ventas (coincidencias): 240773
Filas sin ventas (nulos): 0
Porcentaje de coincidencia: 4.04%

In [18]:
 df_master_t = pd.merge(
    df_master_t,
    df_ventas_enriquecida,
    left_on=['pk_cid', 'pk_partition'],
    right_on=['cid', 'month_sale'],
    how='left'
 )

In [19]:
 cols_to_drop = ['cid', 'month_sale', 'pk_product_ID', 'family_product']
 df_master_t = df_master_t.drop(columns=cols_to_drop)

# cols_to_drop = ['pk_cid', 'pk_partition', 'country_id', 'deceased', 'entry_date',
#                 'pk_sale', 'product_ID', 'pk_product_ID', 'product_desc', 'family_product']
# También podríamos quitar 'active_customer'? Depende, pero la dejamos por ahora

# X = df_master_t.drop(columns=cols_to_drop + ['target'])

In [ ]:
df_master_t

,pk_cid,pk_partition,country_id,region_code,gender,age,deceased,salary,entry_date,entry_channel,...,payroll,pension_plan,payroll_account,emc_account,debit_card,em_acount,pk_sale,product_ID,net_margin,product_desc
0,15891,2018-07,ES,28.0,H,59,N,84876.00,2018-07,KAT,...,0.0,0.0,0,0,0,1,130004.0,4657.0,66.4,em_acount
1,15891,2018-08,ES,28.0,H,59,N,136112.67,2018-07,KAT,...,0.0,0.0,0,0,0,0,NaN,NaN,NaN,NaN
2,16063,2018-11,ES,28.0,H,62,N,87385.62,2018-11,KAT,...,0.0,0.0,0,0,0,0,NaN,NaN,NaN,NaN
3,16063,2018-12,ES,28.0,H,62,N,128867.13,2018-11,KAT,...,0.0,0.0,0,0,0,0,NaN,NaN,NaN,NaN
4,16063,2019-01,ES,28.0,H,62,N,75174.00,2018-11,KAT,...,0.0,0.0,0,0,0,0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6000998,1553685,2019-05,ES,13.0,V,52,N,87385.62,2019-05,KHE,...,0.0,0.0,0,0,0,0,NaN,NaN,NaN,NaN
6000999,1553686,2019-05,ES,41.0,H,30,N,87385.62,2019-05,KHE,...,0.0,0.0,0,0,0,0,NaN,NaN,NaN,NaN
6001000,1553687,2019-05,ES,28.0,V,21,N,87385.62,2019-05,KHE,...,0.0,0.0,0,0,0,0,NaN,NaN,NaN,NaN
6001001,1553688,2019-05,ES,39.0,H,43,N,87385.62,2019-05,KHE,...,0.0,0.0,0,0,0,0,NaN,NaN,NaN,NaN
6001002,1553689,2019-05,ES,21.0,V,40,N,87385.62,2019-05,KHE,...,0.0,0.0,0,0,0,0,NaN,NaN,NaN,NaN

In [20]:
df_master_t = df_master_t.sort_values(by=['pk_partition', 'pk_cid'])

In [21]:
df_master_t = df_master_t[df_master_t['pk_partition'] == '2019-05']
df_master_t

,pk_cid,pk_partition,country_id,region_code,gender,age,deceased,salary,entry_date,entry_channel,...,payroll,pension_plan,payroll_account,emc_account,debit_card,em_acount,pk_sale,product_ID,net_margin,product_desc
8,16063,2019-05,ES,28.0,H,62,N,76113.54,2018-11,KAT,...,0.0,0.0,0,0,0,0,NaN,NaN,NaN,NaN
14,16203,2019-05,ES,8.0,V,70,N,76113.54,2018-12,KAT,...,0.0,0.0,0,0,0,1,NaN,NaN,NaN,NaN
23,16502,2019-05,ES,28.0,H,58,N,76113.54,2018-09,KHN,...,0.0,0.0,0,1,0,1,NaN,NaN,NaN,NaN
40,17457,2019-05,ES,28.0,H,54,N,102405.75,2017-09,KAT,...,0.0,0.0,0,0,1,1,NaN,NaN,NaN,NaN
51,17590,2019-05,ES,28.0,V,55,N,407281.11,2016-12,KAT,...,0.0,0.0,0,0,0,0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6000998,1553685,2019-05,ES,13.0,V,52,N,87385.62,2019-05,KHE,...,0.0,0.0,0,0,0,0,NaN,NaN,NaN,NaN
6000999,1553686,2019-05,ES,41.0,H,30,N,87385.62,2019-05,KHE,...,0.0,0.0,0,0,0,0,NaN,NaN,NaN,NaN
6001000,1553687,2019-05,ES,28.0,V,21,N,87385.62,2019-05,KHE,...,0.0,0.0,0,0,0,0,NaN,NaN,NaN,NaN
6001001,1553688,2019-05,ES,39.0,H,43,N,87385.62,2019-05,KHE,...,0.0,0.0,0,0,0,0,NaN,NaN,NaN,NaN
6001002,1553689,2019-05,ES,21.0,V,40,N,87385.62,2019-05,KHE,...,0.0,0.0,0,0,0,0,NaN,NaN,NaN,NaN

In [ ]:
df_master_t['pk_cid'].value_counts()[lambda x: x > 1]

pk_cid
1465864    5
1527545    5
1547241    5
1546434    5
1544167    4
          ..
1478336    2
1451257    2
1548629    2
1548590    2
1548696    2
Name: count, Length: 1456, dtype: int64

In [ ]:
df_master_t[df_master_t['pk_cid'] == 1465864]

,pk_cid,pk_partition,country_id,region_code,gender,age,deceased,salary,entry_date,entry_channel,...,payroll,pension_plan,payroll_account,emc_account,debit_card,em_acount,pk_sale,product_ID,net_margin,product_desc
5556335,1465864,2019-05,ES,3.0,V,31,N,113890.8,2018-09,KHM,...,1.0,1.0,1,1,1,0,38363.0,2234.0,75.6,payroll
5556336,1465864,2019-05,ES,3.0,V,31,N,113890.8,2018-09,KHM,...,1.0,1.0,1,1,1,0,57578.0,1364.0,8466.3,pension_plan
5556337,1465864,2019-05,ES,3.0,V,31,N,113890.8,2018-09,KHM,...,1.0,1.0,1,1,1,0,75313.0,2235.0,54.9,payroll_account
5556338,1465864,2019-05,ES,3.0,V,31,N,113890.8,2018-09,KHM,...,1.0,1.0,1,1,1,0,88007.0,8871.0,67.9,emc_account
5556339,1465864,2019-05,ES,3.0,V,31,N,113890.8,2018-09,KHM,...,1.0,1.0,1,1,1,0,122543.0,3819.0,60.2,debit_card

In [ ]:
# Limpiamos el dataset
df_master_t['deceased'].value_counts()

deceased
N    445224
Name: count, dtype: int64

In [22]:
df_master_t = df_master_t[df_master_t['deceased'] != 'S']

In [ ]:
df_master_t['active_customer'].value_counts()

active_customer
0.0    271426
1.0    173798
Name: count, dtype: int64

In [23]:
province_map = {
    1: "Álava",
    2: "Albacete",
    3: "Alicante",
    4: "Almería",
    5: "Ávila",
    6: "Badajoz",
    7: "Illes Balears",
    8: "Barcelona",
    9: "Burgos",
    10: "Cáceres",
    11: "Cádiz",
    12: "Castellón",
    13: "Ciudad Real",
    14: "Córdoba",
    15: "A Coruña",
    16: "Cuenca",
    17: "Girona",
    18: "Granada",
    19: "Guadalajara",
    20: "Gipuzkoa",
    21: "Huelva",
    22: "Huesca",
    23: "Jaén",
    24: "León",
    25: "Lleida",
    26: "La Rioja",
    27: "Lugo",
    28: "Madrid",
    29: "Málaga",
    30: "Murcia",
    31: "Navarra",
    32: "Ourense",
    33: "Asturias",
    34: "Palencia",
    35: "Las Palmas",
    36: "Pontevedra",
    37: "Salamanca",
    38: "Santa Cruz de Tenerife",
    39: "Cantabria",
    40: "Segovia",
    41: "Sevilla",
    42: "Soria",
    43: "Tarragona",
    44: "Teruel",
    45: "Toledo",
    46: "Valencia",
    47: "Valladolid",
    48: "Bizkaia",
    49: "Zamora",
    50: "Zaragoza",
    51: "Ceuta",
    52: "Melilla"
}

In [24]:
df_master_t['province'] = df_master_t['region_code'].map(province_map)

/tmp/ipykernel_9095/3723449016.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_master_t['province'] = df_master_t['region_code'].map(province_map)

In [ ]:
df_master_t['province'].value_counts()

province
Madrid                    1197093
Barcelona                  603510
Valencia                   360322
Murcia                     298058
Sevilla                    292254
A Coruña                   255714
Málaga                     189115
Pontevedra                 176459
Alicante                   172813
Cádiz                      161813
Asturias                   135211
Zaragoza                   133598
Badajoz                    122930
Las Palmas                 122898
Valladolid                 117584
Granada                    103462
Toledo                     102970
Salamanca                   92928
Cáceres                     83528
Córdoba                     75817
Huelva                      72409
Albacete                    72356
Ciudad Real                 70372
Cantabria                   70172
Castellón                   69144
Illes Balears               62943
Ourense                     54786
Lugo                        52895
Tarragona                   52044
Girona                      50971
Burgos                      48033
Lleida                      47052
Cuenca                      36188
León                        35737
Bizkaia                     35525
La Rioja                    34967
Almería                     32986
Navarra                     31399
Jaén                        31265
Zamora                      31089
Santa Cruz de Tenerife      29336
Palencia                    27685
Guadalajara                 26980
Segovia                     21774
Ávila                       21424
Huesca                      21203
Gipuzkoa                    19019
Álava                       13068
Teruel                      12640
Soria                        8544
Ceuta                        2930
Melilla                      2659
Name: count, dtype: int64

In [ ]:
# A continuación, se segmentan las provincias en tres grupos en función del volumen de clientes:

# Grupo 1 (Core Markets): formado por Madrid y Barcelona, que concentran la mayor parte de la base de clientes y representan el núcleo principal del negocio.
# Grupo 2 (Growth Markets): incluye aquellas provincias con más de 100.000 clientes, caracterizadas por un volumen relevante y potencial de crecimiento.
# Grupo 3 (Long Tail): engloba el resto de provincias, con menor volumen de clientes y un peso relativo inferior dentro del total.

# Esta segmentación permite priorizar estrategias diferenciadas según la relevancia de cada mercado.

In [25]:
def segment_province(province):
    Provincias_principales = ['Madrid', 'Barcelona', 'Valencia', 'Murcia', 'Sevilla', 'A Coruña']
    Provincias_en_crecimiento = ['Málaga','Pontevedra', 'Alicante', 'Cádiz', 'Asturias', 'Zaragoza', 'Badajoz', 'Las Palmas', 'Valladolid', 'Granada', 'Toledo']

    if province in Provincias_principales:
        return 'Provincias principales'
    elif province in Provincias_en_crecimiento:
        return 'Provincias en crecimiento'
    else:
        return 'Provincias más pequeñas'

df_master_t['province_segment'] = df_master_t['province'].apply(segment_province)

/tmp/ipykernel_9095/877404068.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_master_t['province_segment'] = df_master_t['province'].apply(segment_province)

In [ ]:
df_master_t['province_segment'].value_counts()

province_segment
Provincias principales       227410
Provincias en crecimiento    111127
Provincias más pequeñas      106687
Name: count, dtype: int64

# **Clusterización**

In [ ]:
# Creamos variables temporales en df_master_t

In [26]:
from datetime import datetime

# Convertir entry_date a datetime
df_master_t['entry_date'] = pd.to_datetime(df_master_t['entry_date'], format='%Y-%m')

# Fecha de referencia = última fecha del dataset
fecha_corte = df_master_t['entry_date'].max()

# Calcular meses desde la entrada
df_master_t['months_since_entry'] = (
    (fecha_corte.year - df_master_t['entry_date'].dt.year) * 12 +
    (fecha_corte.month - df_master_t['entry_date'].dt.month)
)

/tmp/ipykernel_9095/171151020.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_master_t['entry_date'] = pd.to_datetime(df_master_t['entry_date'], format='%Y-%m')
/tmp/ipykernel_9095/171151020.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_master_t['months_since_entry'] = (

In [ ]:
# A) Crear dataset A (última partición)

In [ ]:
df_master_t.info()

<class 'pandas.core.frame.DataFrame'>
Index: 445224 entries, 8 to 6001002
Data columns (total 35 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   pk_cid              445224 non-null  int64
 1   pk_partition        445224 non-null  object
 2   country_id          445224 non-null  object
 3   region_code         445224 non-null  float64
 4   gender              445224 non-null  object
 5   age                 445224 non-null  int64
 6   deceased            445224 non-null  object
 7   salary              445224 non-null  float64
 8   entry_date          445224 non-null  datetime64[ns]
 9   entry_channel       445224 non-null  object
 10  active_customer     445224 non-null  float64
 11  segment             445224 non-null  object
 12  short_term_deposit  445224 non-null  int64
 13  loans               445224 non-null  int64
 14  mortgage            445224 non-null  int64
 15  funds               445224 non-null  int64
 16  securities          445224 non-null  int64
 17  long_term_deposit   445224 non-null  int64
 18  credit_card         445224 non-null  int64
 19  payroll             445224 non-null  float64
 20  pension_plan        445224 non-null  float64
 21  payroll_account     445224 non-null  int64
 22  emc_account         445224 non-null  int64
 23  debit_card          445224 non-null  int64
 24  em_acount           445224 non-null  int64
 25  pk_sale             10211 non-null   float64
 26  cid                 10211 non-null   float64
 27  month_sale          10211 non-null   object
 28  product_ID          10211 non-null   float64
 29  net_margin          10211 non-null   float64
 30  pk_product_ID       10211 non-null   float64
 31  product_desc        10211 non-null   object
 32  family_product      10211 non-null   object
 33  province            445060 non-null  object
 34  months_since_entry  445224 non-null  int32
dtypes: datetime64[ns](1), float64(10), int32(1), int64(13), object(10)
memory usage: 120.6+ MB

In [27]:
# Última partición disponible
last_partition = df_master_t['pk_partition'].max()

df_last = df_master_t[df_master_t['pk_partition'] == last_partition].copy()

vars_last = [
    'pk_cid',
    'age',
    'salary',
    'province_segment',
    'active_customer',
    'segment',
    'short_term_deposit', 'funds', 'securities',
    'long_term_deposit', 'credit_card', 'payroll', 'pension_plan',
    'payroll_account', 'emc_account', 'debit_card', 'em_acount',
    'months_since_entry'
]

df_last = df_last[vars_last]

In [ ]:
# B) Crear dataset B (histórico agrupado)

In [30]:
df_hist = df_master_t.groupby('pk_cid').agg({
    'net_margin': ['sum'],
    'pk_sale': 'count',

})

df_hist.columns = [
    'net_margin_sum',
    'num_sales',

]

df_hist = df_hist.reset_index()

In [ ]:
# C) Merge final

In [31]:
df_final = df_last.merge(df_hist, on='pk_cid', how='left')
X = df_final.drop(columns=['pk_cid']).copy()

In [ ]:
X

,age,salary,entry_channel_reduced,gender,active_customer,segment,short_term_deposit,funds,securities,long_term_deposit,credit_card,payroll,pension_plan,payroll_account,emc_account,debit_card,em_acount,months_since_entry,net_margin_sum,num_sales
0,62,76113.54,KAT,H,0.0,02 - PARTICULARES,0,0,0,0,0,0.0,0.0,0,0,0,0,6,0.0,0
1,70,76113.54,KAT,V,1.0,01 - TOP,0,0,0,0,0,0.0,0.0,0,0,0,1,5,0.0,0
2,58,76113.54,other,H,1.0,02 - PARTICULARES,0,0,0,0,0,0.0,0.0,0,1,0,1,8,0.0,0
3,54,102405.75,KAT,H,1.0,02 - PARTICULARES,0,0,0,1,0,0.0,0.0,0,0,1,1,20,0.0,0
4,55,407281.11,KAT,V,1.0,02 - PARTICULARES,0,0,0,0,0,0.0,0.0,0,0,0,0,29,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
445219,52,87385.62,KHE,V,0.0,03 - UNIVERSITARIO,0,0,0,0,0,0.0,0.0,0,0,0,0,0,0.0,0
445220,30,87385.62,KHE,H,0.0,03 - UNIVERSITARIO,0,0,0,0,0,0.0,0.0,0,0,0,0,0,0.0,0
445221,21,87385.62,KHE,V,0.0,03 - UNIVERSITARIO,0,0,0,0,0,0.0,0.0,0,0,0,0,0,0.0,0
445222,43,87385.62,KHE,H,0.0,03 - UNIVERSITARIO,0,0,0,0,0,0.0,0.0,0,0,0,0,0,0.0,0
445223,40,87385.62,KHE,V,0.0,03 - UNIVERSITARIO,0,0,0,0,0,0.0,0.0,0,0,0,0,0,0.0,0

In [32]:
# Normalizaremos dos variables: Salary y Net_margin_sum
log_vars = ['salary', 'net_margin_sum']

# Crearemos columnas transformadas con log1p
for col in log_vars:
    df_final[f'{col}_log'] = np.log1p(df_final[col])

# Reemplazaremos las columnas originales por las transformadas
for col in log_vars:
    df_final[col] = df_final[f'{col}_log']
    df_final.drop(columns=[f'{col}_log'], inplace=True)

In [ ]:
# numerical_features y categorical features:

In [33]:
df_master_t['short_term_deposit'].value_counts()

short_term_deposit
0    445222
1         2
Name: count, dtype: int64

In [34]:
# -----------------------------
# Definir variables numéricas
# -----------------------------
numerical_features = [
    'age',
    'salary',
    'months_since_entry',
    'net_margin_sum',
    'num_sales',

    # Variables binarias de productos
    'payroll',
    'pension_plan',
    'payroll_account',
    'emc_account',
    'debit_card',

    # Variables binarias adicionales
    'active_customer'
]


# -----------------------------
# Definir variables categóricas
# -----------------------------
categorical_features = [
    'segment',
    'province_segment'
]


# -----------------------------
# Unir todas las features
# -----------------------------
features_for_clustering = numerical_features + categorical_features

# -----------------------------
# Mostrar información
# -----------------------------
print(f"Cantidad de características numéricas: {len(numerical_features)}")
print(f"Cantidad de características categóricas: {len(categorical_features)}")
print(f"Total de características seleccionadas: {len(features_for_clustering)}")

print("\nPrimeras 5 filas del DataFrame X para clustering:")
display(X.head())

Cantidad de características numéricas: 11
Cantidad de características categóricas: 2
Total de características seleccionadas: 13

Primeras 5 filas del DataFrame X para clustering:

,age,salary,province_segment,active_customer,segment,short_term_deposit,funds,securities,long_term_deposit,credit_card,payroll,pension_plan,payroll_account,emc_account,debit_card,em_acount,months_since_entry,net_margin_sum,num_sales
0,62,76113.54,Provincias principales,0.0,02 - PARTICULARES,0,0,0,0,0,0.0,0.0,0,0,0,0,6,0.0,0
1,70,76113.54,Provincias principales,1.0,01 - TOP,0,0,0,0,0,0.0,0.0,0,0,0,1,5,0.0,0
2,58,76113.54,Provincias principales,1.0,02 - PARTICULARES,0,0,0,0,0,0.0,0.0,0,1,0,1,8,0.0,0
3,54,102405.75,Provincias principales,1.0,02 - PARTICULARES,0,0,0,1,0,0.0,0.0,0,0,1,1,20,0.0,0
4,55,407281.11,Provincias principales,1.0,02 - PARTICULARES,0,0,0,0,0,0.0,0.0,0,0,0,0,29,0.0,0

In [35]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import KNNImputer

# -----------------------------
# Pipeline de preprocesado
# -----------------------------

numerical_transformer = Pipeline(steps=[
    ('imputer', KNNImputer(n_neighbors=5)),
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features)
    ]
)

clustering_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('kmeans', KMeans(random_state=42, n_init=30))
])

print("Pipeline de clustering definido con éxito:")
print(clustering_pipeline)

Pipeline de clustering definido con éxito:
Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   KNNImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'salary',
                                                   'months_since_entry',
                                                   'net_margin_sum',
                                                   'num_sales', 'payroll',
                                                   'pension_plan',
                                                   'payroll_account',
                                                   'emc_account', 'debit_card',
                                                   'active_customer']),
                                                 ('cat',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['segment',
                                                   'province_segment'])])),
                ('kmeans', KMeans(n_init=30, random_state=42))])

In [36]:
# -----------------------------
# Entrenamiento final
# -----------------------------
k_optimal = 4

# Actualizar número de clusters de forma segura
clustering_pipeline.set_params(kmeans__n_clusters=k_optimal)

# Entrenar pipeline completo
clustering_pipeline.fit(X)

# Obtener etiquetas
cluster_labels = clustering_pipeline.predict(X)

# Añadir clusters al dataset
X_with_clusters = X.copy()
X_with_clusters['cluster'] = cluster_labels

print(f"Clusters asignados a {X_with_clusters.shape[0]} clientes con k={k_optimal}.")
display(X_with_clusters.head())

Exception ignored on calling ctypes callback function: <function ThreadpoolController._find_libraries_with_dl_iterate_phdr.<locals>.match_library_callback at 0x78e59cbbf100>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/threadpoolctl.py", line 1005, in match_library_callback
    self._make_controller_from_path(filepath)
  File "/usr/local/lib/python3.12/dist-packages/threadpoolctl.py", line 1187, in _make_controller_from_path
    lib_controller = controller_class(
                     ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/threadpoolctl.py", line 114, in __init__
    self.dynlib = ctypes.CDLL(filepath, mode=_RTLD_NOLOAD)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ctypes/__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: dlopen() error

Clusters asignados a 445224 clientes con k=4.

,age,salary,province_segment,active_customer,segment,short_term_deposit,funds,securities,long_term_deposit,credit_card,payroll,pension_plan,payroll_account,emc_account,debit_card,em_acount,months_since_entry,net_margin_sum,num_sales,cluster
0,62,76113.54,Provincias principales,0.0,02 - PARTICULARES,0,0,0,0,0,0.0,0.0,0,0,0,0,6,0.0,0,2
1,70,76113.54,Provincias principales,1.0,01 - TOP,0,0,0,0,0,0.0,0.0,0,0,0,1,5,0.0,0,2
2,58,76113.54,Provincias principales,1.0,02 - PARTICULARES,0,0,0,0,0,0.0,0.0,0,1,0,1,8,0.0,0,2
3,54,102405.75,Provincias principales,1.0,02 - PARTICULARES,0,0,0,1,0,0.0,0.0,0,0,1,1,20,0.0,0,2
4,55,407281.11,Provincias principales,1.0,02 - PARTICULARES,0,0,0,0,0,0.0,0.0,0,0,0,0,29,0.0,0,2

In [37]:
# -----------------------------
# Perfilado de clusters
# -----------------------------

# Tamaño de cada cluster
cluster_sizes = (
    X_with_clusters['cluster']
    .value_counts()
    .sort_index()
    .to_frame(name='count_customers')
)

# Variables que se agregan por MEDIANA
median_vars = [
    'age',
    'months_since_entry',
    'num_sales'
]

median_df = (
    X_with_clusters
    .groupby('cluster')[median_vars]
    .median()
)

# Variables que se agregan por MODA
mode_vars = [
    'active_customer',
    'segment',
]

mode_df = (
    X_with_clusters
    .groupby('cluster')[mode_vars]
    .agg(lambda x: x.mode().iloc[0] if not x.mode().empty else None)
)


# Variables que se agregan por MEDIA
mean_vars = ['salary', 'net_margin_sum', 'pension_plan', 'payroll_account', 'emc_account', 'debit_card','payroll']

means_df = (
    X_with_clusters
    .groupby('cluster')[mean_vars]
    .mean()
)

means_df.columns = [f"{col}_mean" for col in means_df.columns]

# Unión final
cluster_profile_df = pd.concat(
    [cluster_sizes, median_df, mode_df, means_df],
    axis=1
)

# Ordenar columnas
desired_order = [
    'count_customers',
    'age',
    'months_since_entry',
    'payroll_mean', 'pension_plan_mean', 'payroll_account_mean', 'emc_account_mean', 'debit_card_mean',
    'active_customer',
    'segment',
    'num_sales',
    'salary_mean',
    'net_margin_sum_mean'
]

cluster_profile_df = cluster_profile_df[desired_order]

cluster_profile_df

,count_customers,age,months_since_entry,payroll_mean,pension_plan_mean,payroll_account_mean,emc_account_mean,debit_card_mean,active_customer,segment,num_sales,salary_mean,net_margin_sum_mean
cluster,,,,,,,,,,,,,
0,317344,23.0,22.0,0.000000,0.000050,0.006970,0.000296,0.000246,0.0,03 - UNIVERSITARIO,0.0,108337.667754,0.199526
1,3263,32.0,8.0,0.969353,0.999387,0.698743,0.104505,0.389212,1.0,02 - PARTICULARES,3.0,105442.613316,6193.353203
2,108518,43.0,20.0,0.000000,0.000590,0.074577,0.191710,0.297481,1.0,02 - PARTICULARES,0.0,112695.938519,4.143749
3,16099,35.0,25.0,0.945090,1.000000,0.963352,0.236971,0.661656,1.0,02 - PARTICULARES,0.0,110970.582708,4.578763

In [38]:
# Mapeo de nombres de clusters
cluster_name_map = {
    0: "Jóvenes universitarios con baja vinculación",
    1: "Clientes premium altamente rentables",
    2: "Adultos con baja vinculación y potencial de crecimiento",
    3: "Clientes vinculados con alta adopción de productos"
}

# Asegurar que el índice sea único y mapear nombres de clusters
cluster_profile_df = cluster_profile_df.reset_index(drop=True)  # reset para evitar duplicados
cluster_profile_df.index = cluster_profile_df.index.map(lambda x: cluster_name_map.get(x, f"Cluster {x}"))
cluster_profile_df.index.name = 'Cluster Name'

# Seleccionar columnas numéricas para el heatmap
numerical_cols_for_heatmap = cluster_profile_df.select_dtypes(include=np.number).columns

# Aplicar estilo con gradiente y formato
styled_cluster_profile = (
    cluster_profile_df
    .style
    .background_gradient(cmap='Blues', subset=numerical_cols_for_heatmap)
    .format(precision=2)
)

# Mostrar el DataFrame estilizado
display(styled_cluster_profile)

In [ ]:
# Quitar segmento y provincia
# moda numericas --> median
# productos financieros --> mean
# Dividir entre ciudades grandes o zonas grandes y zonas más deshabitadas (demografico)

En el análisis de los clusters identificados en la base de clientes, se observan cuatro segmentos claramente diferenciados, cada uno con características y oportunidades estratégicas diferentes.

El primer segmentos corresponde a los jóvenes universitarios con baja vinculación, que representan el grupo más numeroso con 317.344 clientes y una media de edad de 23 años. Estos clientes presentan un bajo nivel de contratación de productos financieros y un margen neto prácticamente nulo, reflejando su limitada vinculación con la entidad. Aunque actualmente no estén generando una rentabilidad, este grupo posee un alto potencial de crecimiento en el largo plazo, por lo que resulta estratégico implementar acciones de fidelización temprana y ofrecer productos adaptados a su etapa de vida, como cuentas para estudiantes o servicios de educación financiera.

El segundo segmento está compuesto por los clientes premium altamente rentables, un pequeño grupo de 3.263 clientes con una edad media de 32 años. Se caracterizan por una adopción elevada de productos financieros, alta actividad y un margen neto significativamente superior al resto de segmentos. Este grupo representa el núcleo de rentabilidad de la entidad y requiere estrategias de fidelización personalizada y servicios exlusivos, así como oportunidades de cross-selling para maximizar su valor.

El tercer segmento lo constituyen los adultos con baja vinculación y potencial de crecimiento, con 108.518 clientes y una edad media de 43 años. Aunque presentan cierta actividad y vinculación parcial con algunos productos, su número de ventas y margen neto es bajo. Este grupo se identifica como una oportunidad clave para incrementar la vinculación mediante campañas de fidelización, promoción de productos de ahorro y pensión, y estrategias de cross-selling que incrementen su contribución a la rentabilidad de la entidad.

Finalmente, el cuarto segmento corresponde a los clientes vinculados con alta adopción de productos, conformado por 16.099 clientes de 35 años de media. Aunque muestran un amplio de productos y alta actividad, su margen neto es moderado en comparación con los clientes premium. Este grupo refleja estabilidad y un grado significativo de fidelización, por lo que las estrategias recomendadas se centran en fortalecer la relación con programas de fidelización avanzada y aumentar la rentabilidad mediante productos complementarios.

En cojunto, estos cuatro segmentos permiten a la entidad identificar claramente oportunidades de crecimiento, optimización de la rentabilidad y personalización de estrategias comerciales, proporcionando una base sólida para la toma de decisiones estratégicas basadas en datos.

# **PCA**

In [ ]:
# -----------------------------
# Definir variables numéricas
# -----------------------------
numerical_features = [
    'age',
    'salary',
    'months_since_entry',
    'net_margin_sum',
    'num_sales',

    # Variables binarias de productos
    'payroll',
    'pension_plan',
    'payroll_account',
    'emc_account',
    'debit_card',

    # Variables binarias adicionales
    'active_customer'
]


# -----------------------------
# Definir variables categóricas
# -----------------------------
categorical_features = [
    'segment',
]


# -----------------------------
# Unir todas las features
# -----------------------------
features_for_clustering = numerical_features + categorical_features

# -----------------------------
# Mostrar información
# -----------------------------
print(f"Cantidad de características numéricas: {len(numerical_features)}")
print(f"Cantidad de características categóricas: {len(categorical_features)}")
print(f"Total de características seleccionadas: {len(features_for_clustering)}")

print("\nPrimeras 5 filas del DataFrame X para clustering:")
display(X.head())

Cantidad de características numéricas: 11
Cantidad de características categóricas: 1
Total de características seleccionadas: 12

Primeras 5 filas del DataFrame X para clustering:

,age,salary,province_segment,active_customer,segment,short_term_deposit,funds,securities,long_term_deposit,credit_card,payroll,pension_plan,payroll_account,emc_account,debit_card,em_acount,months_since_entry,net_margin_sum,num_sales
0,62,76113.54,Provincias principales,0.0,02 - PARTICULARES,0,0,0,0,0,0.0,0.0,0,0,0,0,6,0.0,0
1,70,76113.54,Provincias principales,1.0,01 - TOP,0,0,0,0,0,0.0,0.0,0,0,0,1,5,0.0,0
2,58,76113.54,Provincias principales,1.0,02 - PARTICULARES,0,0,0,0,0,0.0,0.0,0,1,0,1,8,0.0,0
3,54,102405.75,Provincias principales,1.0,02 - PARTICULARES,0,0,0,1,0,0.0,0.0,0,0,1,1,20,0.0,0
4,55,407281.11,Provincias principales,1.0,02 - PARTICULARES,0,0,0,0,0,0.0,0.0,0,0,0,0,29,0.0,0

In [ ]:
# A continuación haré un análisis de PCA.

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import KNNImputer
from sklearn.decomposition import PCA

# -----------------------------
# Transformadores
# -----------------------------
numerical_transformer = Pipeline(steps=[
    ('imputer', KNNImputer(n_neighbors=5)),
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])

# -----------------------------
# Preprocessor
# -----------------------------
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features)
    ]
)

# -----------------------------
# Pipeline final con PCA
# -----------------------------
clustering_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('pca', PCA(n_components=0.95, random_state=42)),
    ('kmeans', KMeans(random_state=42, n_init=30))
])

print("Pipeline de clustering definido con éxito:")
print(clustering_pipeline)

Pipeline de clustering definido con éxito:
Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   KNNImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'salary',
                                                   'months_since_entry',
                                                   'net_margin_sum',
                                                   'num_sales', 'payroll',
                                                   'pension_plan',
                                                   'payroll_account',
                                                   'emc_account', 'debit_card',
                                                   'active_customer']),
                                                 ('cat',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['segment'])])),
                ('pca', PCA(n_components=0.95, random_state=42)),
                ('kmeans', KMeans(n_init=30, random_state=42))])

In [ ]:
# -----------------------------
# Entrenamiento final con PCA
# -----------------------------
k_optimal = 4

# Actualizar número de clusters dentro del pipeline
clustering_pipeline.set_params(kmeans__n_clusters=k_optimal)

# Entrenar pipeline completo (preprocesado → PCA → KMeans)
clustering_pipeline.fit(X)

# Obtener etiquetas de cluster
cluster_labels = clustering_pipeline.predict(X)

# Añadir clusters al dataset original
X_with_clusters = X.copy()
X_with_clusters['cluster'] = cluster_labels

print(f"Clusters asignados a {X_with_clusters.shape[0]} clientes con k={k_optimal}.")
display(X_with_clusters.head())

Clusters asignados a 445224 clientes con k=4.

,age,salary,province_segment,active_customer,segment,short_term_deposit,funds,securities,long_term_deposit,credit_card,payroll,pension_plan,payroll_account,emc_account,debit_card,em_acount,months_since_entry,net_margin_sum,num_sales,cluster
0,62,76113.54,Provincias principales,0.0,02 - PARTICULARES,0,0,0,0,0,0.0,0.0,0,0,0,0,6,0.0,0,0
1,70,76113.54,Provincias principales,1.0,01 - TOP,0,0,0,0,0,0.0,0.0,0,0,0,1,5,0.0,0,0
2,58,76113.54,Provincias principales,1.0,02 - PARTICULARES,0,0,0,0,0,0.0,0.0,0,1,0,1,8,0.0,0,0
3,54,102405.75,Provincias principales,1.0,02 - PARTICULARES,0,0,0,1,0,0.0,0.0,0,0,1,1,20,0.0,0,0
4,55,407281.11,Provincias principales,1.0,02 - PARTICULARES,0,0,0,0,0,0.0,0.0,0,0,0,0,29,0.0,0,0

In [ ]:
# -----------------------------
# Perfilado de clusters (compatible con PCA)
# -----------------------------


# -----------------------------
# Tamaño de cada cluster
# -----------------------------
cluster_sizes = (
    X_with_clusters['cluster']
    .value_counts()
    .sort_index()
    .to_frame(name='count_customers')
)

# -----------------------------
# Variables agregadas por MEDIANA
# -----------------------------
median_vars = ['age', 'months_since_entry', 'num_sales']

median_df = (
    X_with_clusters
    .groupby('cluster')[median_vars]
    .median()
)

# -----------------------------
# Variables agregadas por MODA
# -----------------------------
mode_vars = ['active_customer', 'segment']

mode_df = (
    X_with_clusters
    .groupby('cluster')[mode_vars]
    .agg(lambda x: x.mode().iloc[0] if not x.mode().empty else None)
)

# -----------------------------
# Variables agregadas por MEDIA
# -----------------------------
mean_vars = ['salary', 'net_margin_sum', 'pension_plan', 'payroll_account', 'emc_account', 'debit_card', 'payroll']

means_df = (
    X_with_clusters
    .groupby('cluster')[mean_vars]
    .mean()
)

# Renombrar columnas de media
means_df.columns = [f"{col}_mean" for col in means_df.columns]

# -----------------------------
# Unión final
# -----------------------------
cluster_profile_df = pd.concat([cluster_sizes, median_df, mode_df, means_df], axis=1)

# -----------------------------
# Ordenar columnas
# -----------------------------
desired_order = [
    'count_customers',
    'age',
    'months_since_entry',
    'payroll_mean', 'pension_plan_mean', 'payroll_account_mean', 'emc_account_mean', 'debit_card_mean',
    'active_customer',
    'segment',
    'num_sales',
    'salary_mean',
    'net_margin_sum_mean'
]

cluster_profile_df = cluster_profile_df[desired_order]

# -----------------------------
# Mostrar el DataFrame final
# -----------------------------
cluster_profile_df

,count_customers,age,months_since_entry,payroll_mean,pension_plan_mean,payroll_account_mean,emc_account_mean,debit_card_mean,active_customer,segment,num_sales,salary_mean,net_margin_sum_mean
cluster,,,,,,,,,,,,,
0,107978,43.0,20.0,0.000000,0.000593,0.074923,0.192697,0.298996,1.0,02 - PARTICULARES,0.0,112687.150200,4.166915
1,317884,23.0,22.0,0.000000,0.000050,0.006968,0.000286,0.000236,0.0,03 - UNIVERSITARIO,0.0,108348.056485,0.198357
2,16087,35.0,25.0,0.945049,1.000000,0.963324,0.236589,0.661404,1.0,02 - PARTICULARES,0.0,110983.616924,4.432132
3,3275,32.0,8.0,0.969466,0.999389,0.699847,0.106870,0.391450,1.0,02 - PARTICULARES,3.0,105398.843606,6171.397038

In [ ]:
# De nuevo realizando el análisis PCA nos aparece que el clúster 4 es el tipo de perfil más rentable, sin embargo, no hemos conseguido
# reducir el número de columnas quedándonos con el 95% de la varianza total del modelo.

## 1. Problemática: Segmentación de Clientes para Optimización Estratégica

Este apartado aborda la necesidad de comprender en profundidad la base de clientes de la entidad. La problemática central reside en la falta de una visión clara y diferenciada de los distintos perfiles de clientes, lo que dificulta la implementación de estrategias de marketing personalizadas, la gestión proactiva de la relación con el cliente (CRM) y la identificación de oportunidades de negocio específicas. El análisis busca resolver preguntas clave como: ¿quiénes son nuestros clientes más valiosos? ¿Qué segmentos presentan mayor potencial de crecimiento? ¿Qué productos son más atractivos para cada grupo? ¿Cómo podemos optimizar la rentabilidad de cada segmento?

## 2. Solución Aplicada: Clustering de Clientes con Preparación y Transformación de Datos

La solución implementada se enfoca en la segmentación de clientes mediante técnicas de clustering, combinando información sociodemográfica, comercial y de productos. El proceso se ha resuelto en varias etapas:

1.  **Integración y Limpieza de Datos**: Se consolidaron múltiples fuentes de datos (sociodemográficos, actividad comercial, productos y ventas) en un único *DataFrame* maestro (`df_master_t`). Se realizó una limpieza exhaustiva, eliminando columnas redundantes y gestionando valores nulos mediante imputación estratégica (mediana para `salary`, moda para variables categóricas como `gender`, `segment`, `region_code`, `payroll`, `pension_plan`).
2.  **Ingeniería de Características**: Se crearon nuevas variables clave como `months_since_entry` para medir la antigüedad del cliente y `province_segment` para categorizar provincias según el volumen de clientes, enriqueciendo así el perfil de cada individuo.
3.  **Clustering de Clientes (KMeans)**: Se aplicó el algoritmo de K-Means para agrupar a los clientes en segmentos homogéneos. Antes del clustering, los datos fueron preprocesados utilizando:
    *   `KNNImputer` para manejar nulos remanentes.
    *   `StandardScaler` para normalizar las características numéricas, asegurando que ninguna variable dominara el proceso de agrupamiento.
    *   `OneHotEncoder` para transformar las variables categóricas en un formato adecuado para el algoritmo.
4.  **Análisis de Componentes Principales (PCA)**: Se exploró el uso de PCA para reducir la dimensionalidad y simplificar el modelo, manteniendo el 95% de la varianza total. Aunque no se logró una reducción significativa en el número de componentes manteniendo este umbral, se incluyó en el pipeline para evaluar su impacto.
5.  **Perfilado de Clusters**: Cada clúster resultante fue perfilado detalladamente, analizando las características medias, medianas y modas de las variables originales. Esto permitió asignar nombres descriptivos a cada segmento (e.g., "Jóvenes universitarios con baja vinculación", "Clientes premium altamente rentables"), facilitando la comprensión y la toma de decisiones estratégicas.

## 3. Implementación: Tecnología y Encaje

### Tecnología

La solución ha sido desarrollada íntegramente en el entorno de Google Colab, aprovechando su infraestructura y las siguientes herramientas y librerías de Python:

*   **Pandas**: Para la manipulación, limpieza e integración de los datos.
*   **Scikit-learn**: Para la implementación de los algoritmos de preprocesamiento (`StandardScaler`, `OneHotEncoder`, `KNNImputer`), reducción de dimensionalidad (`PCA`) y clustering (`KMeans`).
*   **Dython**: Utilizada para el análisis de correlaciones y asociaciones entre variables.
*   **Matplotlib y Seaborn**: Para la visualización de los datos y el perfilado de los clusters, permitiendo una comprensión gráfica de los resultados.
*   **Numpy y PIL (Pillow)**: Utilizadas para operaciones numéricas y manejo de imágenes, respectivamente, asegurando la compatibilidad de versiones en el entorno.

### Encaje Web (Potencial)

Aunque el presente notebook se centra en el análisis y la creación de los segmentos de clientes, los resultados obtenidos son directamente aplicables a un entorno web y de negocio:

*   **Plataformas de CRM**: Los perfiles de cliente y las etiquetas de clúster (`cluster`) pueden integrarse en sistemas de CRM (Customer Relationship Management) existentes, permitiendo a los equipos de ventas y marketing acceder a información segmentada para interacciones más personalizadas.
*   **Campañas de Marketing Digital**: Los segmentos pueden utilizarse para dirigir campañas publicitarias en plataformas digitales, optimizando la inversión y aumentando la efectividad de las promociones mediante ofertas adaptadas a las necesidades y comportamientos de cada grupo.
*   **Personalización de Contenidos**: En una aplicación web o móvil, los resultados del clustering pueden alimentar motores de recomendación, ofreciendo productos, servicios o contenidos personalizados a cada usuario en función de su segmento de pertenencia.
*   **Dashboards de Negocio**: Los perfiles de clúster pueden visualizarse en *dashboards* interactivos (por ejemplo, con herramientas como Tableau, Power BI o Dash de Plotly) para que la dirección y los equipos de negocio puedan monitorear la evolución de los segmentos y tomar decisiones estratégicas basadas en datos en tiempo real.
*   **API de Clasificación**: El modelo de clustering entrenado podría ser expuesto como un servicio RESTful (API) para clasificar nuevos clientes o actualizar la segmentación de clientes existentes en tiempo real dentro de una aplicación.